### ISSUE TITLE
Nothing changes in Mixpanel after Import

### ISSUE THREAD

**Issue by secoint** [mixpanel/mixpanel-ruby#102]
Hello!

I use the following code to import some events in the past:
```ruby
tracker = ConveadMixpanel::Tracker.new(MIXPANEL_TOKEN)
tracker.people.set(user_id, payload)  # create user first

tracker.import(MIXPANEL_API_SECRET, user_id, "$signup", {'time' => user.created_at.to_i})
```
Is responds with `true`, but nothing changes in Mixpanel! I can see my user, but there are no events in his activity feed.

I also tried with curl like it is described in the docs:
```
curl https://api.mixpanel.com/import \
-u API_TOKEN \
-d data=BASE64_ENCODED_JSON \
verbose=1
```
It responds with `{"status": 1, "error": null}` and again nothing in Mixpanel

What I'm doing wrong?

P.S. `user.created_at` is a few days ago.
P.P.S. `tracker.track` works great, this issue relates to `.import` only.

**Comment by zakj** [comment]
hi @secoint, the import method (and API endpoint) requires authentication via your mixpanel api *key*, which will be different from your api secret or token. if you can point me to the incorrect docs I'll make sure to get those updated!

**Comment by secoint** [comment]
Thanks @zakj, now it works! But [documentation](https://mixpanel.com/help/reference/importing-old-events) says I should use an **API secret** - that sounds a bit ambiguous: http://take.ms/J3zyf

And it is very confusing that API Secret is listed in Project settings right next to project token.

Thanks again!

**Comment by samihda** [comment]
Commenting in case somebody comes across this issue

I also kept getting `{"status": 1, "error": null}` responses without seeing any results, but finally got it working using the **API secret** as the docs said:

```bash
curl https://api.mixpanel.com/import \
-u API_SECRET: \
-d data=BASE64_ENCODED_JSON \
-d verbose=1 \
-X POST
```
Note: the `-X` flag, which is not currently mentioned in the docs.

**Comment by Emixam23** [comment]
@samihda I have the same, did you figure the issue?

**Comment by Emixam23** [comment]
Well I just opened an issue at https://github.com/mixpanel/mixpanel_api/issues/20 (hopefully i am on the right github)

Thanks for your help, it's just so frustrating because I am stuff on it for a while now and I am not sure to understand why it doesn't work..

To me the issue is that, I have nothing in mixpanel about a signup action in the 5th of january, which means the data didn't get received by mixpanel. However, I keep getting `{"status": 1, "error": null} `, so does the 1 means it worked?

**Comment by samihda** [comment]
I don't remember, but maybe 1 means error here (even though there's no more details under the `error` key). In any case, if it works, you should be able to see the results on the Mixpanel dashboard obviously.

**Comment by Emixam23** [comment]
Dam it :( I tried to give wrong data (and created errors) and I do get a status:0 with an error describing the issue. But when everything seems valid, then I get a status:1 with error equal to null
