### ISSUE TITLE
Group Analytics 

### ISSUE THREAD

**Issue by masudhossain** [mixpanel/mixpanel-ruby#112]
Curious if Group Analytics is available through the mixpanel API. Specifically creating, adding users, etc. 

Additional information: https://developer.mixpanel.com/docs#section-group-analytics

**Comment by patedit** [comment]
Hi @masudhossain! you can check [this article](https://developer.mixpanel.com/docs/http#section-group-analytics) to know how to accomplish this through APIs! Thanks for writing!

**Comment by kikihakiem** [comment]
I think this is already fixed by this PR #114 . Could you guys please make a release for this feature?

**Comment by andrewpurcell** [comment]
supported in https://rubygems.org/gems/mixpanel-ruby/versions/2.2.2
