### ISSUE TITLE
Tracking calls should swallow consumer exceptions in default events and people classes

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-ruby#12]
Throwing an exception in Consumer.send on failure is probably the right thing to do, but the exception should not be propegated through the standard people and events tracking calls - clients rarely want to halt on tracking failures, and requiring try: catch: boilerplate around all calls noises up code, and is a bit wasteful if those calls might later send delegate to buffering or out-of-process consumers. Tracking calls should return falsy values if they detect immediate failures, and folks who want more universal error handling for consumers should use block constructors to catch and deal with the consumer exceptions.

**Comment by zyskowsk** [comment]
this functionality was added in the release of version 2.0.0
