### ISSUE TITLE
How to show city, country, OS

### ISSUE THREAD

**Issue by CARocha** [mixpanel/mixpanel-ruby#122]
Hi, I try to use this library, but I don't see in dashboards city, country, OS
in my method i put this
$mixpanel.track(current_user.id, 'Visit the home page')

<img width="1300" alt="Screen Shot 2023-05-30 at 8 55 49 PM" src="https://github.com/mixpanel/mixpanel-ruby/assets/168115/03b117e6-d346-479a-b7ca-b85193da0da7">

but the city say (not set) equal country and OS
how do i make them appear??

any idea o help

**Comment by imaras** [comment]
Hi @CARocha, I had the same problem (not seeing city, nor country entries in the dashboard) with the difference that I was using C# to send events to Mixpanel. Solution in my case was to make a HTTP POST request to mixpanel track API with query param ip set to 1. In my case I was making a HTTP POST request to https://api-eu.mixpanel.com/track?ip=1. Query param ip=1 instructs Mixpanel to use the ip address of the incoming request to populate city and country entries.
