### ISSUE TITLE
people.set unexpectedly updates 'Last Seen'

### ISSUE THREAD

**Issue by tomjmcdaniel** [mixpanel/mixpanel-ruby#22]
_Last Seen_ seems to be conflated with `profile.updated_at`  

I'm updating a users' profile via mixpanel-ruby to reflect changes made from an administrative UI (ie. User.disabled = false) that we would like to share with Mixpanel _without_ confusing this with a user event in the Mixpanel People/Explore UI.

Instead of using _Last Seen_, then, should I explicitly set a _Last Page Load_ timestamp via the JS client which we can use to differentiate JS client updates from ruby client updates?

**Comment by aug-riedinger** [comment]
Well it would be nice if we could have a hand on this, like do an update on multiple entries at once.

**Comment by ilan-senexx** [comment]
Hi @joeatwork , 
you wrote "in addition to ignoring the time and ip, you can also set them to different values. To see the list of possible optional_params, you can check out our HTTP protocol docs at" 

how can i update $last_seen?

i tried
```
 tracker.people.set(15, {'$last_seen' => 10.day.ago} ,0 ,{'$ignore_time' => 'true'})
```

can you clarify
tnx
