### ISSUE TITLE
response_body returning as �V*.I,)-V�R0�QPJ-*�/��Jsrj��9

### ISSUE THREAD

**Issue by kevinjasker** [mixpanel/mixpanel-ruby#37]
Having an odd issue when sending events. Response comes back and raises the following error - 

```
<Mixpanel::ConnectionError: Could not write to Mixpanel, server responded with 200 returning: '�V*.I,)-V�R0�QPJ-*�/��Jsrj��9'>
```

Event registers in mixpanel, and works fine...

Any ideas?

**Comment by brandonkboswell** [comment]
I am also running into this problem. I am unable to get event the simplest event to return successfully from the Mixpanel Library. Again similar to what @kevinjasker ran into the events are being tracked correctly in mixpanel.

**Comment by arittr** [comment]
hey @brandonkboswell - sorry to hear you're running into this issue. if you could answer Joe's questions we can start digging into what might be going on here: 

1) Are you using a particular URL, parameters, or HTTP headers other than the default when you send? In some circumstances, the MixpanelAPI will serve a 1x1px image, although this is only when you ask specifically for an image in response. If we're very lucky, it's also possible to request a gzipped response that might not be expected by the client.

2) Is the process running the request doing so under any sort of strange network circumstances? It's possible something like this could be the result of corruption on the network.

3) What network library are you using, and are you using that library simultaneously in multiple threads? It's a longshot, but if the response isn't getting corrupted on the wire or isn't the result of some unexpected or strange server response, perhaps the Mixpanel library is tripping over something in the HTTP client itself.

sorry for the trouble and frustration here - let us know!
