### ISSUE TITLE
500/Mixpanel down errors throw unpredictable exceptions from consumer

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-ruby#51]
Reported by @theonegri in comments of #12 -regardless of the resolution of that issue, the library shouldn't throw exceptions in these circumstances, since we don't know that the relevant callers will still be around.

We still need to decide how to best indicate that an error has occurred, so that callers who care to can retry or log the issue.

**Comment by mmmurf** [comment]
maybe allow callers to pass in a proc that does something in the event of a tracking error?  also returning false would be fine... with today's api outage I'm forced to add error handling code in multiple places in my app.

**Comment by zyskowsk** [comment]
As of version 2.0.0 the consumer rescues `StandardError` and raises a `MixpanelError`.
