### ISSUE TITLE
People set with optional param $ignore_time does not work. Last Seen always updated

### ISSUE THREAD

**Issue by jwicks** [mixpanel/mixpanel-ruby#54]
```ruby
      tracker.people.set(u.id, {
        '$first_name' => u.first_name,
        '$last_name' => u.last_name,
        '$email' => u.email
      }, optional_params = {
        # For server-side updates, do not update last seen and geolocation
        '$ignore_time' => true,
        '$ip' => '0'
      })
```
When run, Last Seen is always updated to "less than a minute ago" on Mixpanel.  This should not happen per Mixpanel [docs](https://mixpanel.com/help/reference/http#people-analytics-updates). $ip => '0' works correctly, as geolocation properties are not updated from server-side IP address.

As a workaround I'm using Typhoeus against Mixpanel's HTTP API, here is the equivalent request.

```ruby
      data = Base64.encode64({
        '$token' => ENV['MIXPANEL_API_TOKEN'],
        '$ip' => '0', # Do not update geolocation from server-side
        '$ignore_time' => true, # Do not update Last Seen from server-side
        '$distinct_id' => u.id,
        '$set' => {
          '$first_name' => u.first_name,
          '$last_name' => u.last_name,
          '$email' => u.email
        }
      }.to_json)
      request = Typhoeus::Request.new(
        'https://api.mixpanel.com/engage/',
        method: :get,
        params: { data: data, verbose: 1 }
      )
```

With this request, $ignore_time is functioning correctly.

**Comment by kennym** [comment]
I have the exact same issue. How can we prevent the "Last Seen" to be updated, when we use the `tracker.people.set` API method

**Comment by zyskowsk** [comment]
Hey @kennym, I will look into this issue and try to get a prq up with a fix asap, thanks for the note!

**Comment by zyskowsk** [comment]
It appears to be an unfortunate historical decision to have `ip` accepted as the third parameter

**Comment by zyskowsk** [comment]
It looks like this is not a bug, but it is an unfortunate historical artifact in the API.  After some initial thought I think I would prefer to remove the ip parameter globally and update the docs to make it more obvious out to pass ip, ignore_time, and other such parameters in the library.  This change would require a major version bump.  I have opened a new issue #80, further discussion should take place there, and this will be revisited when I am ready to release the next major version of the library.  For now please continue to pass ip as the third parameter of your people calls, not in optional_params as @joeatwork outlined:

```ruby
tracker.people.set(
    u.id, 
    {
        '$first_name' => u.first_name,
        '$last_name' => u.last_name,
        '$email' => u.email,
     }, 
    '0', #ip 
    {'$ignore_time' => true}, #optional_params
)
```

**Comment by kennym** [comment]
@zyskowsk thank you, that fixed my issue.
