### ISSUE TITLE
Request Fails, Resulting in response_body returning as �V*.I,)-V�R0�QPJ-*�/��Jsrj��9

### ISSUE THREAD

**Issue by brandonkboswell** [mixpanel/mixpanel-ruby#59]
Having exact same problem as was mentioned in: https://github.com/mixpanel/mixpanel-ruby/issues/37

I am unable to get even the simplest event to return successfully from the Mixpanel Library. Again similar to what @kevinjasker ran into. The events are being tracked correctly in mixpanel, however the Ruby library seems to think they failed.

**Comment by joeatwork** [comment]
I hate to celebrate your bug, but we're very interested in your ability to reproduce this issue! It sounds like you can reproduce this issue every time.

Would you mind taking a moment to answer the following questions?

- What OS are you running on? Can you reproduce this issue in multiple environments or only on a single machine?
- What version of ruby are you using?
- Are you using the latest version of the Mixpanel-Ruby gem? (that's 1.6.0 right now) - if not, what version are you using?
- Are you using Mixpanel.config_http?
- Are you using Mixpanel from multiple threads?

Any other info you can think of would also really help!

Most of all, though, thanks for confirming this bug!

**Comment by brandonkboswell** [comment]
@joeatwork 

OS: In Development it's Mac OS X Yosemite 10.10.2. Haven't pushed this into production yet, so not sure if this affects other OS'es.
Ruby Version: 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
Mixpanel-Ruby Gem Version: 1.6.0
Mixpanel Config: Not Using Any Custom Config
Threading: We're Using Puma, Running Multiple Threads and Multiple Workers (However we're not doing anything odd with Puma and this error happens consistently, not just some of the time).

Let me know if you have any other questions.

**Comment by joeatwork** [comment]
Fantastic! This is a big help!

**Comment by brandonkboswell** [comment]
Just a note on this. Just upgraded to 2.0.1 and this is no longer an issue.

**Comment by zyskowsk** [comment]
@brandonkboswell great to hear!
