### ISSUE TITLE
README.md is outdated

### ISSUE THREAD

**Issue by dstosik** [mixpanel/mixpanel-ruby#62]
Hello,

Trying to see what's the difference between 1.4.0 and 1.7.0, I searched for a changelog, and only found an incomplete one in the readme file (it only goes to 1.4.0).
I'd like to know what are the changes since 1.4.0, and see if there's anything I need to do to get 1.7.0 to work properly on my existing installation that's running 1.4.0.

Thanks,
David

**Comment by zyskowsk** [comment]
Hey @dstosik sorry this, it was simply laziness on our part.  The README has been update for 2.0.0 and we will continue it for further releases.  Thanks again for your contributions!

**Comment by dstosik** [comment]
Thanks!
