### ISSUE TITLE
Fine tune default timeouts

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-ruby#63]
Current timeouts are too short for users in some parts of the world, however, we don't want to introduce too much unexpected variability into batch jobs. We should fine-tune our default timeouts to contain most (but not all) real-world timings during normal server operation.

See #61 for some discussion

**Comment by dstosik** [comment]
:+1:

**Comment by zyskowsk** [comment]
@dstosik, what would be reasonable timeouts for you in Japan? I would like to fine tune these but also don't want them to be to to generous

**Comment by zyskowsk** [comment]
addressed in v2.2.0 #88
