### ISSUE TITLE
 undefined method `continue_timeout=' for #<Net::HTTP api.mixpanel.com:443 open=false>

### ISSUE THREAD

**Issue by aunderwo** [mixpanel/mixpanel-ruby#65]
Getting a number of timeout errors that result in a rails error

    undefined method `continue_timeout=' for #<Net::HTTP api.mixpanel.com:443 open=false>
    .bundle/gems/ruby/1.9.1/gems/mixpanel-ruby-1.7.0/lib/mixpanel-ruby/consumer.rb:119:in `request'

This is when running ruby 1.9.2

**Comment by joeatwork** [comment]
Sorry for the error! We need to be more formally aware of the versions of ruby we support in our gem, and either support this version or note that it isn't supported at gem install time.

**Comment by joeatwork** [comment]
at the very least, we need to add spec.required_ruby_version to the gemspec

**Comment by zyskowsk** [comment]
Hey @aunderwo!  Thanks for the comment, as of version 2.0.0 we have included a required ruby version of 2.0.0, although our tests are passing on 1.9.3 so that might be enough!
