### ISSUE TITLE
`Mixpanel::BufferedConsumer#send` has no deprecation?

### ISSUE THREAD

**Issue by PikachuEXE** [mixpanel/mixpanel-ruby#67]
While `Mixpanel::Consumer#send` has deprecation?
Might worth mentioning the removed method as part of upgrade note

**Comment by zyskowsk** [comment]
@PikachuEXE Thanks for the message!  This was an oversight on my part, will push a patch this morning

**Comment by zyskowsk** [comment]
fixed in patch 2.0.1
