### ISSUE TITLE
Expose Meaningful Errors To Caller

### ISSUE THREAD

**Issue by jonmchan** [mixpanel/mixpanel-ruby#89]
When you call Mixpanel::Tracker#track or Mixpanel::Tracker#import, all errors are caught and not sent to the calling application (https://github.com/mixpanel/mixpanel-ruby/blob/master/lib/mixpanel-ruby/events.rb#L125). I would like to suggest a change where the calling application receives the error along with what event/properties were attempted to send. 

Without further information to why the call failed, it is impossible to debug the system. Was it an improper token? Bad data sent? Was mixpanel just momentarily unavailable? The MixpanelError should be exposed to the calling application so that the application can decide if it needs to resend the data or log an error.

**Comment by zyskowsk** [comment]
Hey @jonmchan! Thanks for reaching out.  While it was a conscious decision on my part to silence all errors thrown in the consumer, there is currently a lot of discussion around how to make it easier for people to handle MixpanelErrors in any way they want.  I encourage you to check out #85 which is the proposed plan for custom error handlers.

**Comment by zyskowsk** [comment]
merged in v2.2.0 #88
