### ISSUE TITLE
send event error.

### ISSUE THREAD

**Issue by motephyr** [mixpanel/mixpanel-ruby#92]
i try to use the gem for server api data analytic,but i didn't trigger it.

I try this:
gem install 'mixpanel-ruby'
require 'mixpanel-ruby'
t = Mixpanel::Tracker.new('MYTOKEN')
t.track(1,'A Mixpanel Event')

it just give me
'=> false'

I didn't see the action data working the panel,please check it.

**Comment by zyskowsk** [comment]
Hey @motephyr!  Thanks for reaching out, is it possible that this is a problem with your integration?  I would suggest reaching out to support@mixpanel.com, they would be more than happy to help you troubleshoot this.

**Comment by railsme** [comment]
```
class Mixpanel::ErrorHandler
  def handle(error)
    puts error
  end
end
```
and mixpanel will show you error message :)

**Comment by motephyr** [comment]
ok, I got error message.

Thank you!
